In [59]:
import pytest
import regression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import log_loss
import numpy as np

In [82]:
X_train, X_val, y_train, y_val = regression.utils.loadDataset(
    features=[
        'Penicillin V Potassium 500 MG',
        'Computed tomography of chest and abdomen',
        'Plain chest X-ray (procedure)',
        'Low Density Lipoprotein Cholesterol',
        'Creatinine',
        'AGE_DIAGNOSIS'
    ],
    split_percent=0.8,
    split_seed=42
)

# Scale the data, since values vary across feature. Note that we
# fit on the training data and use the same scaler for X_val.
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_val = sc.transform(X_val)

# For testing purposes, once you've added your code.
# CAUTION: hyperparameters have not been optimized.
log_model = regression.logreg.LogisticRegressor(num_feats=6, learning_rate=0.00001, tol=0.01, max_iter=10, batch_size=10)

X_val = np.hstack([X_val, np.ones((X_val.shape[0], 1))])
preds = log_model.make_prediction(X_val)[0:10]

# check that we get the expected number of predictions
#assert np.shape(preds) == np.shape(X_val)

In [86]:
preds

array([0.01522036, 0.47635533, 0.34717643, 0.65219967, 0.75931417,
       0.97971614, 0.87240443, 0.03239509, 0.66737156, 0.05356135])

In [85]:
preds

array([0.01522036, 0.47635533, 0.34717643, 0.65219967, 0.75931417,
       0.97971614, 0.87240443, 0.03239509, 0.66737156, 0.05356135])

In [29]:
losses = log_model.loss_function(y_val, log_model.make_prediction(X_val))
losses

0.7260681224143479

In [34]:
y_val

array([1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,

In [88]:
my_losses = log_model.loss_function(y_val, log_model.make_prediction(X_val))
sklearn_losses = log_loss(y_val, log_model.make_prediction(X_val))

sklearn_losses

1.038799153793048

In [89]:
my_losses

1.038799153793048

In [90]:
gradient = log_model.calculate_gradient(y_val, X_val)
gradient

array([-0.4665516 , -0.12096683, -0.22550362,  0.        ,  0.        ,
       -0.03226216,  0.09417312])

In [43]:
log_model.W

array([-0.59419986,  0.10745435,  1.83399985, -0.95008541,  0.71772143,
        0.76705803,  0.38425104])

In [45]:
log_model.W != np.random.randn(6 + 1).flatten()

array([ True,  True,  True,  True,  True,  True,  True])